/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-12-01 09:52:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findPwChange_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../_header.jsp", out, false);
      out.write("\r\n");
      out.write("<script src=\"/Farmstory2/js/validation.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("	$('.btnNext').click(function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("	\r\n");
      out.write("		let pass1 = $('input[name=pass1]').val();\r\n");
      out.write("		let pass2 = $('input[name=pass2]').val();\r\n");
      out.write("	\r\n");
      out.write("		if(pass1 == pass2){\r\n");
      out.write("						\r\n");
      out.write("			if(pass2.match(regPass)){\r\n");
      out.write("				\r\n");
      out.write("				let uid = $('#uid').text();\r\n");
      out.write("				\r\n");
      out.write("				let jsonData = {\r\n");
      out.write("						\"uid\": uid,\r\n");
      out.write("						\"pass\": pass2\r\n");
      out.write("				};\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: '/Farmstory2/user/findPwChange.do',\r\n");
      out.write("					method: 'post',\r\n");
      out.write("					data: jsonData,\r\n");
      out.write("					dataType: 'json',\r\n");
      out.write("					success: function(data){\r\n");
      out.write("						\r\n");
      out.write("						if(data.result > 0){\r\n");
      out.write("							alert('비밀번호가 변경되었습니다. \\n로그인을 하시기 바랍니다.');\r\n");
      out.write("							location.href = \"/Farmstory2/user/login.do\";\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			}else{\r\n");
      out.write("				$('.resultPass').css('color', 'red').text('영문, 숫자, 특수문자 조합 최소 5자 이상 이어야 합니다.');\r\n");
      out.write("			}				\r\n");
      out.write("		}else{\r\n");
      out.write("			$('.resultPass').css('color', 'red').text('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("			}			\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<main id=\"user\">\r\n");
      out.write("    <section class=\"find findPwChange\">\r\n");
      out.write("        <form action=\"#\">\r\n");
      out.write("            <table border=\"0\">\r\n");
      out.write("                <caption>비밀번호 변경</caption>                        \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>아이디</td>\r\n");
      out.write("                    <td id=\"uid\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessUserForPw.uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>새 비밀번호</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"password\" name=\"pass1\" placeholder=\"새 비밀번호 입력\"/>\r\n");
      out.write("                    	<span class=\"resultPass\"></span>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>새 비밀번호 확인</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"password\" name=\"pass2\" placeholder=\"새 비밀번호 입력\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>                                        \r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <p>\r\n");
      out.write("            비밀번호를 변경해 주세요.<br>\r\n");
      out.write("            영문, 숫자, 특수문자를 사용하여 8자 이상 입력해 주세요.                    \r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"/Farmstory2/user/login.do\" class=\"btn btnCancel\">취소</a>\r\n");
      out.write("            <a href=\"/Farmstory2/user/login.do\" class=\"btn btnNext\">다음</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</main>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../_footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
