/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-12-01 10:19:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findPw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../_header.jsp", out, false);
      out.write("\r\n");
      out.write("<script src=\"/Farmstory2/js/emailAuth.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	$(function(){\r\n");
      out.write("		\r\n");
      out.write("		$('.btnNext').click(function(e){\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("			\r\n");
      out.write("			if(!isEmailAuthOk){\r\n");
      out.write("				alert('이메일 인증을 하십시요.');\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			let uid = $('input[name=uid]').val();\r\n");
      out.write("			let email = $('input[name=email]').val();\r\n");
      out.write("			\r\n");
      out.write("			let jsonData = {\r\n");
      out.write("					\"uid\": uid,\r\n");
      out.write("					\"email\": email\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: '/Farmstory2/user/findPw.do',\r\n");
      out.write("				type: 'post',\r\n");
      out.write("				data: jsonData,\r\n");
      out.write("				dataType: 'json',\r\n");
      out.write("				success: function(data){\r\n");
      out.write("					\r\n");
      out.write("					if(data.result > 0){\r\n");
      out.write("						location.href= \"/Farmstory2/user/findPwChange.do\";\r\n");
      out.write("					}else{\r\n");
      out.write("						alert('일치하는 회원이 없습니다.\\n이름과 이메일을 다시 확인하시기 바랍니다.');\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<main id=\"user\">\r\n");
      out.write("    <section class=\"find findPw\">\r\n");
      out.write("        <form action=\"#\">\r\n");
      out.write("            <table border=\"0\">\r\n");
      out.write("                <caption>비밀번호 찾기</caption>                        \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>아이디</td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"uid\" placeholder=\"아이디 입력\"/></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>이메일</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <input type=\"email\" name=\"email\" placeholder=\"이메일 입력\"/>\r\n");
      out.write("                            <span class=\"resultEmail\"></span>\r\n");
      out.write("                            <button type=\"button\" class=\"btnAuth\" id=\"btnEmail\">인증번호 받기</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <input type=\"text\" name=\"auth\" placeholder=\"인증번호 입력\"/>\r\n");
      out.write("                            <button type=\"button\" class=\"btnConfirm\" id=\"btnEmailConfirm\">확인</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>                        \r\n");
      out.write("            </table>                                        \r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <p>\r\n");
      out.write("            비밀번호를 찾고자 하는 아이디와 이메일을 입력해 주세요.<br>                    \r\n");
      out.write("            회원가입시 입력한 아이디와 이메일 주소가 같아야, 인증번호를 받을 수 있습니다.<br>\r\n");
      out.write("            인증번호를 입력 후 확인 버튼을 누르세요.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"/Farmstory2/user/login.do\" class=\"btn btnCancel\">취소</a>\r\n");
      out.write("            <a href=\"/Farmstory2/user/findPwChange.do\" class=\"btn btnNext\">다음</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</main>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../_footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
