/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-12-05 05:31:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/java2/Desktop/workspace/JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Farmstory2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669871772988L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./_header.jsp", out, false);
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("	onsole.log('1');\r\n");
      out.write("	\r\n");
      out.write("	// 공지사항 최신글 가져오기\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:'/Farmstory2/board/getLatests.do?cate=notice',\r\n");
      out.write("		method: 'GET',\r\n");
      out.write("		async: false,\r\n");
      out.write("		dataType: 'json',		\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			console.log('2');\r\n");
      out.write("			for(let latest of data){\r\n");
      out.write("				let url = \"/Farmstory2/board/view.do?group=community&cate=notice&no=\"+latest.no+\"&pg=1\";\r\n");
      out.write("				$('#tabs-1 .txt').append(\"<li><a href='\"+url+\"'>\"+latest.title+\"</a></li>\");\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:'/Farmstory2/board/getLatests.do?cate=qna',\r\n");
      out.write("		method:'GET',\r\n");
      out.write("		async: false,\r\n");
      out.write("		dataType:'json',\r\n");
      out.write("		success:function(data){\r\n");
      out.write("			console.log('3');\r\n");
      out.write("			for(let latest of data){\r\n");
      out.write("				let url = \"/Farmstory2/board/view.do?group=community&cate=qna&no=\"+latest.no+\"&pg=1\";\r\n");
      out.write("				$('#tabs-2 .txt').append(\"<li><a href='\"+url+\"'>\"+latest.title+\"</a></li>\");\r\n");
      out.write("			}\r\n");
      out.write("		} \r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:'/Farmstory2/board/getLatests.do?cate=fna',\r\n");
      out.write("		method:'GET',\r\n");
      out.write("		async: false,\r\n");
      out.write("		dataType:'json',\r\n");
      out.write("		success:function(data){\r\n");
      out.write("			console.log('4');\r\n");
      out.write("			for(let latest of data){\r\n");
      out.write("				let url = \"/Farmstory2/board/view.do?group=community&cate=fna&no=\"+latest.no+\"&pg=1\";\r\n");
      out.write("				$('#tabs-3 .txt').append(\"<li><a href='\"+url+\"'>\"+latest.title+\"</a></li>\");\r\n");
      out.write("			}\r\n");
      out.write("		} \r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<main>\r\n");
      out.write("    <div class=\"slider\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><img src=\"/Farmstory2/img/main_slide_img1.jpg\" alt=\"슬라이더1\"></li>\r\n");
      out.write("            <li><img src=\"/Farmstory2/img/main_slide_img2.jpg\" alt=\"슬라이더2\"></li>\r\n");
      out.write("            <li><img src=\"/Farmstory2/img/main_slide_img3.jpg\" alt=\"슬라이더3\"></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <img src=\"/Farmstory2/img/main_slide_img_tit.png\" alt=\"사람과 자연을 사랑하는 팜스토리\"/>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"banner\">\r\n");
      out.write("            <img src=\"/Farmstory2/img/main_banner_txt.png\" alt=\"GRAND OPEN\"/>\r\n");
      out.write("            <img src=\"/Farmstory2/img/main_banner_tit.png\" alt=\"팜스토리 오픈기념 30% 할인 이벤트\"/>\r\n");
      out.write("            <img src=\"/Farmstory2/img/main_banner_img.png\" alt=\"과일\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"quick\">\r\n");
      out.write("        <a href=\"/Farmstory2/board/list.do?group=croptalk&cate=menu\"><img src=\"/Farmstory2/img/main_banner_sub1_tit.png\" alt=\"오늘의 식단\"></a>\r\n");
      out.write("        <a href=\"/Farmstory2/board/list.do?group=croptalk&cate=chef\"><img src=\"/Farmstory2/img/main_banner_sub2_tit.png\" alt=\"나도 요리사\"></a>                \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"latest\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"#\"><img src=\"/Farmstory2/img/main_latest1_tit.png\" alt=\"텃밭 가꾸기\"/></a>\r\n");
      out.write("            <img src=\"/Farmstory2/img/main_latest1_img.jpg\" alt=\"이미지\"/>\r\n");
      out.write("            <table border=\"0\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"#\"><img src=\"/Farmstory2/img/main_latest2_tit.png\" alt=\"귀농학교\"/></a>\r\n");
      out.write("            <img src=\"/Farmstory2/img/main_latest2_img.jpg\" alt=\"이미지\"/>\r\n");
      out.write("            <table border=\"0\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"#\"><img src=\"/Farmstory2/img/main_latest3_tit.png\" alt=\"농작물 이야기\"/></a>\r\n");
      out.write("            <img src=\"/Farmstory2/img/main_latest3_img.jpg\" alt=\"이미지\"/>\r\n");
      out.write("            <table border=\"0\">\r\n");
      out.write("            	");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"info\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <img src=\"/Farmstory2/img/main_sub2_cs_tit.png\" class=\"tit\" alt=\"고객센터 안내\"/>\r\n");
      out.write("            <div class=\"tel\">\r\n");
      out.write("                <img src=\"./img/main_sub2_cs_img.png\" alt=\"\">\r\n");
      out.write("                <img src=\"./img/main_sub2_cs_txt.png\" alt=\"1666-777\">\r\n");
      out.write("                <p class=\"time\">\r\n");
      out.write("                    평일: AM 09:00 ~ PM 06:00<br>\r\n");
      out.write("                    점심: PM 12:00 ~ PM 01:00<br>\r\n");
      out.write("                    토, 일요일, 공휴일 휴무\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btns\">\r\n");
      out.write("                <a href=\"#\"><img src=\"./img/main_sub2_cs_bt1.png\" alt=\"1:1 고객문의\"></a>\r\n");
      out.write("                <a href=\"#\"><img src=\"./img/main_sub2_cs_bt2.png\" alt=\"자주묻는질문\"></a>\r\n");
      out.write("                <a href=\"#\"><img src=\"./img/main_sub2_cs_bt3.png\" alt=\"배송조회\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <img src=\"/Farmstory2/img/main_sub2_account_tit.png\" class=\"tit\" alt=\"계좌안내\"/>\r\n");
      out.write("            <p class=\"account\">\r\n");
      out.write("                기업은행 123-456789-01-01-012<br />\r\n");
      out.write("                국민은행 01-1234-56789<br />\r\n");
      out.write("                우리은행 123-456789-01-01-012<br />\r\n");
      out.write("                하나은행 123-456789-01-01<br />\r\n");
      out.write("                예 금 주 (주)팜스토리\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <div id=\"tabs\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#tabs-1\">공지사항</a></li>\r\n");
      out.write("                    <li><a href=\"#tabs-2\">1:1 고객문의</a></li>\r\n");
      out.write("                    <li><a href=\"#tabs-3\">자주묻는 질문</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div id=\"tabs-1\">\r\n");
      out.write("                    <ul class=\"txt txt-notice\"></ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tabs-2\">\r\n");
      out.write("                     <ul class=\"txt txt-qna\"></ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tabs-3\">\r\n");
      out.write("                     <ul class=\"txt txt-fnq\"></ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./_footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /index.jsp(81,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("latest");
      // /index.jsp(81,16) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /index.jsp(81,16) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(4);
      // /index.jsp(81,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(81,16) '${latests}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${latests}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					 <tr>\r\n");
            out.write("	                    <td>></td>\r\n");
            out.write("	                    <td><a href=\"/Farmstory2/board/view.do?group=croptalk&cate=grow&no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&pg=1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("	                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.rdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("	                </tr>            	\r\n");
            out.write("            	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /index.jsp(94,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("latest");
      // /index.jsp(94,16) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(5);
      // /index.jsp(94,16) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(9);
      // /index.jsp(94,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(94,16) '${latests}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${latests}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					 <tr>\r\n");
            out.write("	                    <td>></td>\r\n");
            out.write("	                    <td><a href=\"/Farmstory2/board/view.do?group=croptalk&cate=school&no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&pg=1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("	                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.rdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("	                </tr>            	\r\n");
            out.write("            	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /index.jsp(107,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("latest");
      // /index.jsp(107,13) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setBegin(10);
      // /index.jsp(107,13) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setEnd(14);
      // /index.jsp(107,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(107,13) '${latests}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${latests}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					 <tr>\r\n");
            out.write("	                    <td>></td>\r\n");
            out.write("	                    <td><a href=\"/Farmstory2/board/view.do?group=croptalk&cate=story&no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&pg=1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("	                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${latest.rdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("	                </tr>            	\r\n");
            out.write("            	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
